import { Article } from '@/types';

export const MOCK_ARTICLES: Article[] = [
  {
    id: '1',
    title: 'Gemini 2.5 Flash released with improved performance',
    url: 'https://example.com/gemini-2.5',
    summary: 'Google released Gemini 2.5 Flash, which is faster and more accurate for coding tasks.',
    group: 'general',
    category: 'core',
    status: 'in_feed',
    published_at: new Date().toISOString(),
    queued_at: null,
  },
  {
    id: '2',
    title: 'New React features in 19.1',
    url: 'https://example.com/react-19-1',
    summary: 'React 19.1 introduces better server component support and hooks.',
    group: 'it_news',
    category: 'related',
    status: 'in_feed',
    published_at: new Date().toISOString(),
    queued_at: null,
  },
  {
    id: '3',
    title: 'Coffee brewing for developers',
    url: 'https://example.com/coffee-dev',
    summary: 'A guide to brewing the perfect coffee for long coding sessions.',
    group: 'it_blog',
    category: 'random',
    status: 'in_feed',
    published_at: new Date().toISOString(),
    queued_at: null,
  },
  {
    id: '4',
    title: 'The future of WebAssembly',
    url: 'https://example.com/wasm-future',
    summary: 'WebAssembly is expanding beyond the browser into server-side runtimes.',
    group: 'it_news',
    category: 'core',
    status: 'in_feed',
    published_at: new Date().toISOString(),
    queued_at: null,
  },
  {
    id: '5',
    title: 'Tailwind CSS v4 is here',
    url: 'https://example.com/tailwind-v4',
    summary: 'Tailwind CSS v4 features a brand new engine and zero-runtime performance.',
    group: 'general',
    category: 'related',
    status: 'in_feed',
    published_at: new Date().toISOString(),
    queued_at: null,
  },
];
